import { Link } from 'react-router-dom';
import { useLang, type Lang } from '../i18n';
import { LangSwitcher } from '../components/LangSwitcher';

const BRAND = 'Florida Biz Labs';
const MARK = '/icons/favicon.svg';

type Section = { h: string; body: string[] };
type Doc = { eyebrow: string; title: string; updated: string; intro: string; sections: Section[] };
type Page = 'privacy' | 'terms' | 'support';

const CONTENT: Record<Page, Record<Lang, Doc>> = {
  privacy: {
    en: {
      eyebrow: 'Privacy', title: 'Privacy Notice', updated: 'Updated July 2026',
      intro: `${BRAND} is an AI research tool. We keep data to the minimum needed to run your account — and we never sell it.`,
      sections: [
        { h: 'What we store', body: [`To sign you in and show your work, we store your account email (and name, if you provide one) and the research summaries you generate. That’s it. We don’t build advertising profiles, track you across the web, or sell or rent your data.`] },
        { h: 'Where the information comes from', body: [`Each summary is generated by AI from public web sources and third-party business listings gathered at the moment you run a search. We link back to those sources and don’t republish or store their content beyond what’s needed to show you the summary and the links.`] },
        { h: 'Your choices', body: [`You can request deletion of your account and your summaries at any time by contacting support.`] },
        { h: 'Contact', body: [`Questions about privacy? Email privacy@floridabizlabs.com.`] },
      ],
    },
    es: {
      eyebrow: 'Privacidad', title: 'Aviso de privacidad', updated: 'Actualizado julio 2026',
      intro: `${BRAND} es una herramienta de investigación con IA. Guardamos los datos mínimos necesarios para tu cuenta — y nunca los vendemos.`,
      sections: [
        { h: 'Qué guardamos', body: [`Para dejarte ingresar y mostrar tu trabajo, guardamos el email de tu cuenta (y tu nombre, si lo das) y los resúmenes de investigación que generas. Eso es todo. No armamos perfiles publicitarios, no te rastreamos por la web, ni vendemos o alquilamos tus datos.`] },
        { h: 'De dónde viene la información', body: [`Cada resumen lo genera la IA a partir de fuentes públicas de la web y avisos de negocios de terceros, recopilados en el momento en que haces una búsqueda. Enlazamos de vuelta a esas fuentes y no republicamos ni almacenamos su contenido más allá de lo necesario para mostrarte el resumen y los enlaces.`] },
        { h: 'Tus opciones', body: [`Puedes pedir la eliminación de tu cuenta y tus resúmenes en cualquier momento contactando a soporte.`] },
        { h: 'Contacto', body: [`¿Dudas de privacidad? Escribe a privacy@floridabizlabs.com.`] },
      ],
    },
    fr: {
      eyebrow: 'Confidentialité', title: 'Avis de confidentialité', updated: 'Mis à jour juillet 2026',
      intro: `${BRAND} est un outil de recherche par IA. Nous conservons le minimum de données nécessaires à votre compte — et nous ne les vendons jamais.`,
      sections: [
        { h: 'Ce que nous conservons', body: [`Pour vous connecter et afficher votre travail, nous conservons l’email de votre compte (et votre nom, si vous le fournissez) et les résumés que vous générez. C’est tout. Nous ne créons pas de profils publicitaires, ne vous suivons pas sur le web, et ne vendons ni ne louons vos données.`] },
        { h: 'D’où vient l’information', body: [`Chaque résumé est généré par IA à partir de sources web publiques et d’annonces d’entreprises tierces, rassemblées au moment de votre recherche. Nous renvoyons vers ces sources et ne republions ni ne stockons leur contenu au-delà du nécessaire pour afficher le résumé et les liens.`] },
        { h: 'Vos choix', body: [`Vous pouvez demander la suppression de votre compte et de vos résumés à tout moment en contactant le support.`] },
        { h: 'Contact', body: [`Des questions sur la confidentialité ? Écrivez à privacy@floridabizlabs.com.`] },
      ],
    },
    pt: {
      eyebrow: 'Privacidade', title: 'Aviso de privacidade', updated: 'Atualizado julho 2026',
      intro: `${BRAND} é uma ferramenta de pesquisa com IA. Guardamos o mínimo de dados necessários para sua conta — e nunca os vendemos.`,
      sections: [
        { h: 'O que guardamos', body: [`Para você entrar e ver seu trabalho, guardamos o email da sua conta (e seu nome, se informar) e os resumos que você gera. Só isso. Não criamos perfis de publicidade, não rastreamos você pela web, nem vendemos ou alugamos seus dados.`] },
        { h: 'De onde vem a informação', body: [`Cada resumo é gerado por IA a partir de fontes públicas da web e anúncios de negócios de terceiros, reunidos no momento em que você faz uma busca. Fazemos link de volta para essas fontes e não republicamos nem armazenamos o conteúdo delas além do necessário para mostrar o resumo e os links.`] },
        { h: 'Suas opções', body: [`Você pode pedir a exclusão da sua conta e dos seus resumos a qualquer momento contatando o suporte.`] },
        { h: 'Contato', body: [`Dúvidas sobre privacidade? Escreva para privacy@floridabizlabs.com.`] },
      ],
    },
  },
  terms: {
    en: {
      eyebrow: 'Legal', title: 'Terms & Disclaimer', updated: 'Updated July 2026',
      intro: `Please read this before using ${BRAND}.`,
      sections: [
        { h: 'Informational only', body: [`${BRAND} produces AI-generated research for informational purposes only. It is not investment, financial, legal, tax or professional advice, and it does not recommend whether to buy any business. Always consult qualified professionals before making a decision.`] },
        { h: 'Accuracy', body: [`AI summaries may be incomplete or inaccurate. Figures come from listings and public sources and are not independently verified. Verify everything yourself before acting.`] },
        { h: 'Source information & ownership', body: [`Business information, listings, prices and related content are compiled from third-party listings and public web sources, and belong to their respective owners, advertisers and listing platforms. ${BRAND} is not affiliated with, endorsed by, or acting on behalf of any listing platform, broker or seller. For complete and current details, always go to the original listing and deal directly through it.`] },
        { h: 'Not a broker', body: [`${BRAND} is not a business broker and is not a party to any transaction between buyers and sellers.`] },
        { h: 'Use at your own risk', body: [`You use ${BRAND} at your own risk. To the extent permitted by law, we disclaim liability for decisions made based on its output.`] },
      ],
    },
    es: {
      eyebrow: 'Legal', title: 'Términos y aviso legal', updated: 'Actualizado julio 2026',
      intro: `Léelo antes de usar ${BRAND}.`,
      sections: [
        { h: 'Solo informativo', body: [`${BRAND} genera investigación con IA solo con fines informativos. No es asesoría de inversión, financiera, legal, fiscal ni profesional, y no recomienda si comprar un negocio. Consulta siempre a profesionales calificados antes de decidir.`] },
        { h: 'Exactitud', body: [`Los resúmenes de IA pueden estar incompletos o ser inexactos. Las cifras provienen de avisos y fuentes públicas y no se verifican de forma independiente. Verifica todo por tu cuenta antes de actuar.`] },
        { h: 'Información de fuentes y propiedad', body: [`La información de negocios, avisos, precios y contenido relacionado se compila de avisos de terceros y fuentes públicas de la web, y pertenece a sus respectivos dueños, anunciantes y plataformas de avisos. ${BRAND} no está afiliado, respaldado ni actúa en nombre de ninguna plataforma de avisos, broker o vendedor. Para detalles completos y actuales, acude siempre al aviso original y opera directamente a través de él.`] },
        { h: 'No es un broker', body: [`${BRAND} no es un broker de negocios y no es parte de ninguna transacción entre compradores y vendedores.`] },
        { h: 'Uso bajo tu propio riesgo', body: [`Usas ${BRAND} bajo tu propio riesgo. En la medida permitida por la ley, no asumimos responsabilidad por decisiones tomadas con base en sus resultados.`] },
      ],
    },
    fr: {
      eyebrow: 'Mentions légales', title: 'Conditions et avertissement', updated: 'Mis à jour juillet 2026',
      intro: `Veuillez lire ceci avant d’utiliser ${BRAND}.`,
      sections: [
        { h: 'À titre informatif uniquement', body: [`${BRAND} produit une recherche générée par IA à titre informatif uniquement. Ce n’est pas un conseil en investissement, financier, juridique, fiscal ou professionnel, et cela ne recommande pas d’acheter une entreprise. Consultez toujours des professionnels qualifiés avant de décider.`] },
        { h: 'Exactitude', body: [`Les résumés IA peuvent être incomplets ou inexacts. Les chiffres proviennent des annonces et de sources publiques et ne sont pas vérifiés de façon indépendante. Vérifiez tout vous-même avant d’agir.`] },
        { h: 'Sources et propriété', body: [`Les informations d’entreprise, annonces, prix et contenus associés sont compilés à partir d’annonces tierces et de sources web publiques, et appartiennent à leurs propriétaires, annonceurs et plateformes respectifs. ${BRAND} n’est ni affilié, ni approuvé, ni agissant au nom d’une plateforme d’annonces, d’un courtier ou d’un vendeur. Pour des détails complets et à jour, consultez toujours l’annonce d’origine et traitez directement via celle-ci.`] },
        { h: 'Pas un courtier', body: [`${BRAND} n’est pas un courtier et n’est partie à aucune transaction entre acheteurs et vendeurs.`] },
        { h: 'À vos risques', body: [`Vous utilisez ${BRAND} à vos propres risques. Dans la mesure permise par la loi, nous déclinons toute responsabilité pour les décisions prises sur la base de ses résultats.`] },
      ],
    },
    pt: {
      eyebrow: 'Jurídico', title: 'Termos e aviso legal', updated: 'Atualizado julho 2026',
      intro: `Leia isto antes de usar a ${BRAND}.`,
      sections: [
        { h: 'Apenas informativo', body: [`A ${BRAND} gera pesquisa com IA apenas para fins informativos. Não é aconselhamento de investimento, financeiro, jurídico, fiscal ou profissional, e não recomenda se você deve comprar um negócio. Consulte sempre profissionais qualificados antes de decidir.`] },
        { h: 'Precisão', body: [`Os resumos de IA podem estar incompletos ou imprecisos. Os números vêm de anúncios e fontes públicas e não são verificados de forma independente. Verifique tudo por conta própria antes de agir.`] },
        { h: 'Informação das fontes e propriedade', body: [`Informações de negócios, anúncios, preços e conteúdo relacionado são compilados de anúncios de terceiros e fontes públicas da web, e pertencem aos seus respectivos donos, anunciantes e plataformas. A ${BRAND} não é afiliada, endossada, nem age em nome de nenhuma plataforma de anúncios, corretor ou vendedor. Para detalhes completos e atuais, vá sempre ao anúncio original e negocie diretamente por ele.`] },
        { h: 'Não é corretora', body: [`A ${BRAND} não é uma corretora de negócios e não é parte de nenhuma transação entre compradores e vendedores.`] },
        { h: 'Uso por sua conta e risco', body: [`Você usa a ${BRAND} por sua conta e risco. Na medida permitida por lei, isentamo-nos de responsabilidade por decisões tomadas com base nos seus resultados.`] },
      ],
    },
  },
  support: {
    en: {
      eyebrow: 'Support', title: 'Support', updated: '',
      intro: `Need help? We’re happy to assist.`,
      sections: [
        { h: 'Contact us', body: [`Email support@floridabizlabs.com and we’ll get back to you, usually within one business day.`] },
        { h: 'Common topics', body: [`Account access and email verification, credits and billing, or questions about a research summary.`] },
        { h: 'A reminder', body: [`${BRAND} is a research aid, not advice. For anything you plan to act on, verify against the original listing and consult a qualified professional.`] },
      ],
    },
    es: {
      eyebrow: 'Soporte', title: 'Soporte', updated: '',
      intro: `¿Necesitas ayuda? Con gusto te asistimos.`,
      sections: [
        { h: 'Contáctanos', body: [`Escribe a support@floridabizlabs.com y te respondemos, normalmente en un día hábil.`] },
        { h: 'Temas comunes', body: [`Acceso a la cuenta y verificación de email, créditos y facturación, o dudas sobre un resumen de investigación.`] },
        { h: 'Un recordatorio', body: [`${BRAND} es una ayuda de investigación, no asesoría. Para algo sobre lo que vayas a actuar, verifica con el aviso original y consulta a un profesional calificado.`] },
      ],
    },
    fr: {
      eyebrow: 'Support', title: 'Support', updated: '',
      intro: `Besoin d’aide ? Nous sommes là.`,
      sections: [
        { h: 'Contactez-nous', body: [`Écrivez à support@floridabizlabs.com et nous répondrons, généralement sous un jour ouvré.`] },
        { h: 'Sujets fréquents', body: [`Accès au compte et vérification de l’email, crédits et facturation, ou questions sur un résumé de recherche.`] },
        { h: 'Un rappel', body: [`${BRAND} est une aide à la recherche, pas un conseil. Pour toute action envisagée, vérifiez auprès de l’annonce d’origine et consultez un professionnel qualifié.`] },
      ],
    },
    pt: {
      eyebrow: 'Suporte', title: 'Suporte', updated: '',
      intro: `Precisa de ajuda? Teremos prazer em ajudar.`,
      sections: [
        { h: 'Fale conosco', body: [`Escreva para support@floridabizlabs.com e retornaremos, normalmente em um dia útil.`] },
        { h: 'Temas comuns', body: [`Acesso à conta e verificação de email, créditos e cobrança, ou dúvidas sobre um resumo de pesquisa.`] },
        { h: 'Um lembrete', body: [`A ${BRAND} é um auxílio de pesquisa, não aconselhamento. Para qualquer coisa que você vá agir, verifique no anúncio original e consulte um profissional qualificado.`] },
      ],
    },
  },
};

function LegalShell({ page }: { page: Page }) {
  const { lang } = useLang();
  const doc = CONTENT[page][lang] ?? CONTENT[page].en;
  const homeHref = lang === 'en' ? '/' : `/${lang}`;
  const L: Record<Lang, { home: string; privacy: string; terms: string; support: string }> = {
    en: { home: '← Home', privacy: 'Privacy', terms: 'Legal', support: 'Support' },
    es: { home: '← Inicio', privacy: 'Privacidad', terms: 'Legal', support: 'Soporte' },
    fr: { home: '← Accueil', privacy: 'Confidentialité', terms: 'Mentions légales', support: 'Support' },
    pt: { home: '← Início', privacy: 'Privacidade', terms: 'Jurídico', support: 'Suporte' },
  };
  const l = L[lang] ?? L.en;

  return (
    <div>
      <header className="hdr">
        <div className="container">
          <Link className="brand" to={homeHref}><img className="brand-mark" src={MARK} alt="" width="26" height="26" />{BRAND}</Link>
          <div className="row" style={{ gap: 12 }}>
            <LangSwitcher />
            <Link className="btn btn--black btn--sm" to="/login">Log In</Link>
          </div>
        </div>
      </header>

      <main className="container legal">
        <span className="eyebrow">{doc.eyebrow}</span>
        <h1 className="h-lg" style={{ margin: '10px 0 6px' }}>{doc.title}</h1>
        {doc.updated && <p className="mono muted" style={{ fontSize: 11, marginBottom: 22 }}>{doc.updated}</p>}
        <p className="lead" style={{ maxWidth: '42rem', marginBottom: 34 }}>{doc.intro}</p>
        {doc.sections.map((s) => (
          <section key={s.h} className="legal-sec">
            <h2>{s.h}</h2>
            {s.body.map((p, i) => <p key={i}>{p}</p>)}
          </section>
        ))}
      </main>

      <footer className="foot">
        <div className="container" style={{ display: 'flex', gap: 22, flexWrap: 'wrap', alignItems: 'center' }}>
          <Link to={homeHref} className="mono muted" style={{ fontSize: 11 }}>{l.home}</Link>
          <Link to="/privacy" className="mono muted" style={{ fontSize: 11 }}>{l.privacy}</Link>
          <Link to="/legal" className="mono muted" style={{ fontSize: 11 }}>{l.terms}</Link>
          <Link to="/support" className="mono muted" style={{ fontSize: 11 }}>{l.support}</Link>
        </div>
      </footer>
    </div>
  );
}

export const Privacy = () => <LegalShell page="privacy" />;
export const Terms = () => <LegalShell page="terms" />;
export const Support = () => <LegalShell page="support" />;
